# profiles:
#   active: r4
spring:
  datasource:
    # url: 'jdbc:postgresql://postgresql:5432/hapi'
    # username: admin
    # password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: true


hapi:
  fhir:
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
    fhir_version: R4
    client_id_strategy: ANY
    daoconfig_client_id_strategy: uuid
    delete_expunge_enabled: true